baseURL = 'http://peterjuse.github.io/peter_page/'
languageCode = 'es-Es'
title = 'Peterjuse 127.0.0.1'
theme = 'triple-hyde'

[Menus]
  main = [
      {Name = 'Home', URL = 'http://peterjuse.github.io/peter_page/'}
  ]

[params]
  description = 'Las bizarras aventuras de Pedro'
  themeColor = 'theme-base-1c'
  layoutReverse = true
  mainSections = ['posts']

[params.social]
  email = 'pedro.boll22@gmail.com'
  facebook = 'pedro_luis22'
  gravatar = 'pedro.boll22@gmail.com'
  github = 'peterjuse'
  instagram = 'pedro_luis22'
  linkedin = 'pedroBoll'
  reddit = 'peterjuse'
  twitter = 'pedro_luis22'